// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migwriteraddstaus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migwriteraddstaus));
        
        string IMigrationMetadata.Id
        {
            get { return "202201221750244_mig-writer-add-staus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
